
ALTER TABLE public.moldes ADD COLUMN IF NOT EXISTS template_pdf_url text;

DELETE FROM public.moldes;

INSERT INTO public.moldes (name, category, description, emoji, popular, sort_order, image_url, template_pdf_url) VALUES
('Caixa Milk', 'Caixas', 'Caixinha milk clássica para lembrancinhas e doces', '🥛', true, 1,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Milk.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Milk.pdf'),
('Caixa Milk Vintage', 'Caixas', 'Versão vintage da caixinha milk com recortes decorativos', '🥛', true, 2,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Milk_Vintage.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Milk%20Vintage.pdf'),
('Caixa Cubo', 'Caixas', 'Caixa cúbica clássica para presentes e doces', '📦', false, 3,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Cubo.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Cubo.pdf'),
('Caixa Bala', 'Embalagens', 'Embalagem em formato de bala torcida nas pontas', '🍬', true, 4,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Bala.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Bala.pdf'),
('Caixa Meia Bala', 'Embalagens', 'Meia bala — versão menor da embalagem bala', '🍬', false, 5,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Meia_Bala.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Meia%20Bala.pdf'),
('Caixa Brownie', 'Caixas', 'Caixa retangular ideal para brownies e doces fatiados', '🍫', false, 6,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Brownie.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Brownie.pdf'),
('Caixa Canudo', 'Embalagens', 'Embalagem tubular para canudos recheados', '🌮', false, 7,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Canudo.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Canudo.pdf'),
('Caixa Fina', 'Caixas', 'Caixa fina e elegante para chocolates e bombons', '🍫', false, 8,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Fina.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Fina.pdf'),
('Caixa Mala', 'Caixas', 'Caixa em formato de mala com alça decorativa', '🧳', true, 9,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Mala.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Mala.pdf'),
('Caixa Pipoca', 'Embalagens', 'Balde de pipoca clássico para festas e cinema', '🍿', true, 10,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Pipoca.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Pipoca.pdf'),
('Caixa Porta Tubetes', 'Embalagens', 'Caixa expositora com divisórias para tubetes', '🧪', false, 11,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Porta_Tubetes.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Porta%20Tubetes.pdf'),
('Caixa Saquinho', 'Embalagens', 'Saquinho com fundo em caixa para lembrancinhas', '🛍️', false, 12,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Saquinho.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Saquinho.pdf'),
('Caixa Sextava Gomos', 'Caixas', 'Caixa sextavada com gomos decorativos', '⬡', false, 13,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Sextava_Gomos.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Sextava%20-%20Gomos.pdf'),
('Caixa Sushi', 'Embalagens', 'Caixa estilo sushi para doces e salgados finos', '🍣', false, 14,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Caixa_Sushi.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Caixa%20Sushi.pdf'),
('China In Box', 'Embalagens', 'Caixa estilo comida chinesa take-away', '🥡', true, 15,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/China_In_Box.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/China%20In%20Box.pdf'),
('Cestinha', 'Embalagens', 'Cestinha de papel com alça para guloseimas', '🧺', true, 16,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Cestinha.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Cestinha.pdf'),
('Forminhas', 'Decoração', 'Forminhas decorativas para doces de festa', '🌸', false, 17,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Forminhas.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Forminhas.pdf'),
('Porta Bis Duplo', 'Decoração', 'Porta-bis duplo para personalizar chocolates', '🍫', true, 18,
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/thumbs/Porta_Bis_Duplo.png',
 'https://pemjulrovatvcicnpvbo.supabase.co/storage/v1/object/public/moldes/Porta%20Bis%20Duplo.pdf');
